# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-kubernetes-tfc-cloud-agent
  description: Provision a Terraform Cloud Agent on an existing Kubernetes cluster.
  homepage: https://cloudposse.com/accelerate
  topics: terraform-modules, tfe, terraform-enterprise, tfc, terraform-cloud, agent, kubernetes, kubernetes-deployment, runner, terraform-cloud-runner, tfc-runner, tfe-runner, tfc-agent, tfe-agent



